### ISSUE TITLE
WordPressのバージョン設定

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#102]
WordPressのバージョンが上がる度に、コアファイルの構成が変わってしまうため。  
シェアしているsite.yml内のversion: latest部分を適切なバージョンに変えて全体に展開・共有する。

**Comment by nina-fujioka** [comment]
function.phpの記載は確認済。

**Comment by nina-fujioka** [comment]
対応済みのものはここに書きましょう。  

ex)  
functions.php内に自動アップグレードを停止にして記述すみ。  
site.ymlに関しては対応に関して不明点もあるため確認ください。

**Comment by onishi-nina** [comment]
■対応ファイル
・functions.php
自動アップグレードを停止にして記述すみ。

・site.yml
開発時の最新バーションを記入済み（バージョン4.8で設定）

ご確認ください。
