### ISSUE TITLE
記事一覧系のサムネイルが正しく表示されている

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#103]
表示画像の比率を相談したい。  
できれば、画像サムネイルの生成比率を２パターン持ちたい。  
noimgも２パターン作成する。

**Comment by nina-fujioka** [comment]
▼relatedサムネイルサイズに関して  
左上基準で長方形に画像をクリップしたい。
サイズは251*147の比率。(レスポンシブなのであくまで比率)　　

▼サイドバー内サムネイルサイズに関して  
左上基準で正方形に画像をクリップしたい。
サイズは72*72 (スマホ時もこのサイズでOK)

**Comment by onishi-nina** [comment]
頂いたサイズ感サムネイル画像が書き出せる用に設定しました。
サンプルページでのご確認をお願い致します。

▼サンプルページ
http://nina.dev/%E6%A5%B5%E7%AB%AF%E3%81%AA%E4%BE%8B/title-should-not-overflow-the-content-area

> ▼relatedサムネイルサイズに関して
> 左上基準で長方形に画像をクリップしたい。
> サイズは251*147の比率。(レスポンシブなのであくまで比率)　　
> 
> ▼サイドバー内サムネイルサイズに関して
> 左上基準で正方形に画像をクリップしたい。
> サイズは72*72 (スマホ時もこのサイズでOK)

また「relatedサムネイルサイズに関して」の比率のサイズ（large_thumbnail）をもう1種類と記事のアイキャッチ用（post_thumbnail）に以下のサイズで設定しました。

- large_thumbnail  = 1004x588  (relatedサムネイルサイズの4倍)
- post_thumbnail  = 1506  (横幅が1506pxになる)

不足などありましたら、ご一報ください。

**Comment by nina-fujioka** [comment]
LGTM!!
