### ISSUE TITLE
必要なwpテンプレートタグ挿入されている

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#105]
タイトルどうり

**Comment by nina-fujioka** [comment]
#109

**Comment by nina-fujioka** [comment]
#103 **記事一覧サムネイル**

**Comment by nina-fujioka** [comment]
#110 **目次の実装**

**Comment by nina-fujioka** [comment]
これ、こっちでまきとります

**Comment by onishi-nina** [comment]
着手します

**Comment by nina-fujioka** [comment]
#113 **keywordタグ表示用のテンプレートファイル追加とwpタグの実装**

**Comment by onishi-nina** [comment]
■serviceの固定ページを作成
▼できること（index）
page-service.php

▼UIデザイン
page-ui.php

▼レスポンシブWebデザイン
page-responsive.php

▼ウェブコンサルティング
page-support.php

**Comment by nina-fujioka** [comment]
固定ページ了解です

**Comment by nina-fujioka** [comment]
ex)一旦~~のページに関しての表示に必要なwpテンプレートタグの挿入は完了しています。なので~ページに関しては記事投稿ができるので確認してください。

こちらでサンプルでuiページに関して投稿して確認しています。
http://nina.dev/service/ui  

同じように投稿できると思いますのでそのほかのページに関して投稿を宜しくお願いします。

**Comment by nina-fujioka** [comment]
ここもマスターのイメージ。  
いわば関連タスクの消化の過程でステータスが完了に近づくタスク。
