### ISSUE TITLE
パンくずの表示確認

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#109]
パーマリンクの設定詳細は、wiki007内を参照。  
表示させるページの各phpファイルに、パーマリンク用のテンプレートファイルを読み込ませる？(相談)

**Comment by onishi-nina** [comment]
テンプレートで読み込ませたいですよね。
以下の感じで、パーマリンク用どうですか？

・php
/template_parts/breadcrumb.php

・class
.p-breadcrumb

**Comment by nina-fujioka** [comment]
じゃこれでいきましょう！

**Comment by nina-fujioka** [comment]
着手します

**Comment by nina-fujioka** [comment]
シングルページと固定ページに対しての表示実装対応。  
タグページ類は未着手。 記述が増えてめんどうになりそうなら、  
プラグイン(Breadcrumb NavXT)をつかうかも。

**Comment by nina-fujioka** [comment]
タグページの条件分岐  
is_tag()

**Comment by nina-fujioka** [comment]
ページ内で確認したのでクローズ
