### ISSUE TITLE
目次の実装

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#110]
目次の実装をしたい。  
コンポーネントクラスは、sass内の「c-index」。

▼実装例
タイトル部分：「ざっくり要約すると」  
目次のリスト：本文のh3を抜粋。  

プラグインの使用などはお任せします。

**Comment by onishi-nina** [comment]
実装イメージをメモとして記述するのでご確認ください。
着手する際は、再度お知らせします。

▼実装参考例
http://netaone.com/wp/table-of-contents-plus/
http://hiroki-suzuki.com/table-of-contents-plus

**Comment by nina-fujioka** [comment]
これでおねがいしまーす

**Comment by nina-fujioka** [comment]
受け入れを満たす要件の整理の確認。
↓  
サンプル作成  
↓  
展開

**Comment by nina-fujioka** [comment]
これは来週着手でOK!
