### ISSUE TITLE
カテゴリー整理

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#111]
カテゴリー名の選定・調査など。  
全体の遷移図などを作って、後々に記事にタグを追加した時に効果がでる選定と遷移を実現させる。

**Comment by nina-fujioka** [comment]
# #109 パンくず実装と並行して進める。

**Comment by nina-fujioka** [comment]
![sitemap](https://user-images.githubusercontent.com/29673683/28523236-692ab4c0-70b6-11e7-90fa-3bc8138e2bba.png)

**Comment by nina-fujioka** [comment]
参考資料追加。

**Comment by nina-fujioka** [comment]
![sitemap](https://user-images.githubusercontent.com/29673683/28523577-1028f696-70b8-11e7-9b70-792560e8b42a.png)

**Comment by nina-fujioka** [comment]
![sitemap](https://user-images.githubusercontent.com/29673683/28523659-5c4d6778-70b8-11e7-986b-a75d42feab30.png)

**Comment by nina-fujioka** [comment]
これ、質問箇所があったらきいてください。  

▼記事に関しての基本
**article/postname**    

▼service以下の記事に関して  
**service/responsive** (**article/postname**でも正直よし)  

ここは、どちらでもいいので一番良い形を提案ください。

**Comment by onishi-nina** [comment]
> ▼service以下の記事に関して
> service/responsive (article/postnameでも正直よし)

今後、投稿ページと混在しそうなので、serviceのindexと下層３ページに関しては固定ページで作成して管理したほうが良いかと思いますがどうでしょう？

service以下の記事の表示は以下のようになります。
**service/responsive**

**Comment by nina-fujioka** [comment]
site.ymlに  
`/%category%/%postname%`  

上記追加したが、管理画面で再現できず。。  
調査するので、一旦バージョン管理はimport.sqlで。

**Comment by nina-fujioka** [comment]
wiki007に正式に書き込んだタイミングでcloseさせます。

**Comment by nina-fujioka** [comment]
![sitemap](https://user-images.githubusercontent.com/29673683/28559916-7f9d82da-7153-11e7-803c-50bd2e874ca0.png)

**Comment by nina-fujioka** [comment]
![sitemap](https://user-images.githubusercontent.com/29673683/28570653-0be08d84-717a-11e7-8ccb-094d3a05880a.png)

**Comment by nina-fujioka** [comment]
これ、概念ができたため、クローズします
