### ISSUE TITLE
動的ページの表示確認ができる

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#117]
下は分解したタスクを優先順にまとめてます。  

**関連タスク(優先順位順↓)**  

#105 必要なwpテンプレートタグが挿入されている  
#119 サイドバーで動的表示が確認できる  
#103 記事一覧系のサムネイルが正しく表示されている
#110 目次の表示  
#115  パンくず表示  
#113 keywordタグ表示用のテンプレートファイルデザイン  
#120 cssで表示修正  
#128 noimgを２パターン表示する

**Comment by nina-fujioka** [comment]
上の関連タスクが完了の段階が受け入れ条件になり、closeさせます。

**Comment by onishi-nina** [comment]
投稿記事の「uiデザイン」を管理画面から追加

▼URL
http://nina.dev/service/ui

▼管理画面
http://nina.dev/wp-admin/post.php?post=2086&action=edit

- アイキャッチ画像が出力されないときはアップロードした画像が入ってない可能性があります。
- サイドと記事下の関連記事は新着記事に変更予定。

**Comment by onishi-nina** [comment]
Serviceの記事の追加をお願いしたいです。
パーマリンクは指定したURLに編集してください。

■レスポンシブデザイン
・パーマリンク
http://nina.dev/service/responsive

・カテゴリ
サービス

・タグ
レスポンシブデザイン

■ウェブコンサルティング
・パーマリンク
http://nina.dev/service/support

・カテゴリ
サービス

・タグ
レスポンシブデザイン

about、price、flowは後ほど記載します。

**Comment by nina-fujioka** [comment]
了解です、  

>>■ウェブコンサルティング
・パーマリンク
http://nina.dev/service/support

・タグ
レスポンシブデザイン←これはウェブコンサルティングであり、もっとつけようと思えばSEOとかだよね。  

まー了解です

**Comment by onishi-nina** [comment]
すいません。宜しくお願い致します。

about、price、flowのページは投稿からだとパーマリンクにカテゴリが表示されると思うので
「固定ページ」の投稿をお願いしたいと思っていますが問題ないでしょか？
ご確認をお願い致します。

ex) aboutの場合のパーマリンク
・投稿の場合
http://nina.dev/category/about

・固定ページの場合
http://nina.dev/about

**Comment by nina-fujioka** [comment]
全然大丈夫！やります！  
今日中に動的ページ表示に必要なページにページの反映と作成対応します。

**Comment by onishi-nina** [comment]
お願いします！
パンくずが固定ページの時に表示されていないのと、
ページが無いURLに飛んだ時(404.php)に行った時、
レイアウトが崩れているので、phpのテンプレートファイルを編集します。

以下編集するファイルです。
・/template_parts/p-breadcrumb.php
・/404.php

**Comment by nina-fujioka** [comment]
はーい

**Comment by nina-fujioka** [comment]
動的表示に必要な以下ページ作成対応すみです。    

▼service群(投稿より新規追加)
 ・http://nina.dev/service/responsive/
 ・http://nina.dev/service/support/

▼about群(固定ページより新規追加)
 ・http://nina.dev/about  
 ・http://nina.dev/flow  
(現状サムネイルなし)  
 ・http://nina.dev/price  
(現状サムネイルなし)

**Comment by nina-fujioka** [comment]
ex) 今回の対応でページが揃ったのでご確認ください。  
タスクの受け入れ条件が【動的ページの表示確認ができる】となっているので、  
記事の整合性より先に、  

- 記事が投稿できる。
- URLの確認(遷移)
- タグやアイキャッチの投稿・追加 

などといった、動的に表示が確認できる状態でコミットしています。 　　

次のタスクで今回対応していない記事の整合性に関しては、別タスクで対応するので、  
着手して問題ないようでしたら、ご一報ください。

**Comment by nina-fujioka** [comment]
まあこんな感じでおねがいしゃす！

**Comment by onishi-nina** [comment]
確認できました！ありがとうございました。

**Comment by onishi-nina** [comment]
今回で動的に出力するファイルが揃ったのでご確認ください。

> ▼service群(投稿より新規追加)
>  ・http://nina.dev/service/responsive/
>  ・http://nina.dev/service/support/
> 
> ▼about群(固定ページより新規追加)
>  ・http://nina.dev/about  
>  ・http://nina.dev/flow  
> (現状サムネイルなし)  
>  ・http://nina.dev/price  
> (現状サムネイルなし)  

以下が追加で対応した一覧ページになります。

▼カテゴリ一覧
http://nina.dev/service

▼keyword一覧
http://nina.dev/tag/css

一覧ページの表示は「category.php」「tag.php」は削除して「archive.php」で対応しています。
レイアウト調整に関しては、以下のタスクで対応をお願いします。
https://github.com/nina-dev/dev/issues/120  cssで表示修正

リンク先が無いページに関しての表示崩れは調整しました。
表示内容に関しては別タスクで対応しますので、ご一報ください。

**Comment by nina-fujioka** [comment]
了解です、ありがとーー

**Comment by nina-fujioka** [comment]
書くところなんだけど、関連タスクに記載したほうがいいかも。

**Comment by nina-fujioka** [comment]
たとえば、#119  サイドバーで動的表示が確認できる  
これの状態はどう？

**Comment by nina-fujioka** [comment]
#103 記事一覧系のサムネイルが正しく表示されている
これも状態はどうか

**Comment by nina-fujioka** [comment]
自分のステータスとタスクのステータスを可視化させて、消化の確認を取らせた方がいいかもしれない
