### ISSUE TITLE
サイドバーで動的表示が確認できる

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#119]

**Comment by nina-fujioka** [comment]
![sidebar-type](https://user-images.githubusercontent.com/29673683/28568584-5404f720-7171-11e7-9b94-6eb0978933f4.png)

**Comment by nina-fujioka** [comment]
これを確認して、どう対応するか(どう動くか、また動いてもらうか)を検討し着手ください。

**Comment by nina-fujioka** [comment]
typeはこちら  
https://user-images.githubusercontent.com/29673683/28559916-7f9d82da-7153-11e7-803c-50bd2e874ca0.png

**Comment by nina-fujioka** [comment]
typeはこちら  
https://user-images.githubusercontent.com/29673683/28570653-0be08d84-717a-11e7-8ccb-094d3a05880a.png

**Comment by onishi-nina** [comment]
- **sidebar.phpを４タイプ作成**
- **sidebar.phpを４タイプの出力実装**
- **ページタイプごとにsidebar.phpを設定**

**出力実装の優先順位順↓**
・関連記事
・最新記事
・タグ一覧
・カテゴリ一覧
・サービスへの導線（ui・responsive・support）
・固定ページへの導線（about・flow・price）
・CTAエリア

**Comment by nina-fujioka** [comment]
そうね！動的が主で検討してもらえたらOKです

**Comment by onishi-nina** [comment]
**sidebar.phpを４タイプ作成（ファイル名は相談します）**
・sidebar-type1.php
・sidebar-type2.php
・sidebar-type3.php
・sidebar-type4.php

**sidebar.phpに出力実装済み（表示確認中）**
▼関連記事
・投稿されたタグに紐づく投稿を最大5件表示

▼最新記事
・最新の投稿を5件表示

▼タグ一覧
・タグ全件表示（登録された順で表示）

▼カテゴリ一覧
・カテゴリ全件表示（階層は持たせず、登録された順で表示）

**今後実装予定**
▼サービスへの導線（ui・responsive・support）
▼固定ページへの導線（about・flow・price）
▼CTAエリア

コミットに#119忘れました。対象コミットは以下です。
https://github.com/nina-dev/dev/commit/a0a825996d72c6c8e768b6ef773c111fb5b98fdd
https://github.com/nina-dev/dev/commit/9a71094d4b453bbce5ecadead051716426a44957

**Comment by nina-fujioka** [comment]
OKです！

**Comment by onishi-nina** [comment]
**sidebar.phpを４タイプの出力実装**
各タイプごとに出力項目を追加しました。
・sidebar-type1.php
・sidebar-type2.php
・sidebar-type3.php
・sidebar-type4.php

投稿記事に対して「sidebar-type4.php」の出力処理を追加。
sidebar-type4.php以外の出力はカテゴリーの分岐処理を追加予定です。

**Comment by nina-fujioka** [comment]
現状のサイドバーの状況。 
今後の展開(ゴールに対して必要なもの、相談)etc

**Comment by onishi-nina** [comment]
https://github.com/nina-dev/dev/pull/136/commits/d0813c1f967433b3b78e851b7770b10b5ae55887 サイドバーの出力処理を変更
で以下の対応をしました。

ページタイプごとの表示は以下URLからご確認ください。

▼sidebar-type1.php
http://nina.dev/service
http://nina.dev/tag/comments

▼sidebar-type2.php
http://nina.dev/service/ui
http://nina.dev/service/responsive
http://nina.dev/service/support

▼sidebar-type3.php
http://nina.dev/about
http://nina.dev/flow
http://nina.dev/price

▼sidebar-type4.php
http://nina.dev/%E6%A5%B5%E7%AB%AF%E3%81%AA%E4%BE%8B/title-should-not-overflow-the-content-area

**Comment by onishi-nina** [comment]
今回の対応でサイドバーが揃ったのでご確認ください。
タスクの受け入れ条件が【サイドバーで動的表示が確認できる】となっているので、

- 関連記事が表示される
- 最新記事が表示される
- タグ・カテゴリー一覧が表示される
- ページタイプ・URLごとに表示する項目を切り分ける

といった動的に表示が確認できる状態でコミットしています。 　　

また、about、price、flowなどの
静的で繋いでいるリンクのサムネイル画像はダミーを表示しているので
変更する際は差し替えてください。

以下がファイルパスになります。
サイズは800x467を使用しています。

**・ニナ・アーキタイプについて**
http://nina.dev/wp-content/themes/nina/img/article/about.jpg

**・お仕事の流れについて**
http://nina.dev/wp-content/themes/nina/img/article/flow.jpg

**・プロジェクトの形態や規模、期間に応じて柔軟にご提案させていただきます。（料金ページ）**
http://nina.dev/wp-content/themes/nina/img/article/price.jpg

**・レスポンシブ**
http://nina.dev/wp-content/themes/nina/img/article/responsive.jpg

**・ウェブコンサル**
http://nina.dev/wp-content/themes/nina/img/article/support.jpg

**・コンテンツ力を引き出す、心地よいUIデザインを提供します（UI）**
http://nina.dev/wp-content/themes/nina/img/article/ui.jpg
