### ISSUE TITLE
【ページ作成と導線の整備】/contact追加

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#139]
目的：クライアントとのコニュニケーションを作り、問い合わせに対応させたい。  
方法：/contact/にコンタクトフォームを作成する。  

要望：
- ユーザーがフォーム入力をした後、指定のメアドにスムーズに届き、コニュニケーションを作りたい。
- ユーザーが不便を感じずに送信完了まで自然と進める誘導をさせたい。  
- ナビゲーションの導線からもコンタクトフォームに遷移できる導線を作りたい。
    
以上が条件。

実現方法 :  
要望を満たす、実装・デザインを作るためのヒアリングはおまかせします。  
ヒアリング前の整理は#140 を参考に。

・ポイント
- まず、当たり前をつくる整備をすること。
- どのようにすれば着手できるかを考える事(いきなり着手はできないはず)
- フォーム単体でとらえないこと。サイト内(/contact)のフォームであることを忘れない。  

以上を自分のテーブルに並べてみる。 

そこで、最適な方法を「選ぶ」。←大事。  
その上で必要なポイントをつける。

**Comment by onishi-nina** [comment]
▼ヒアリング前の要望を整理

**- ユーザーがフォーム入力をした後、指定のメアドにスムーズに届き、コニュニケーションを作りたい。**
ユーザーのお問い合わせ確定後の動きを、ユーザに迷わせないようする。

**- ユーザーが不便を感じずに送信完了まで自然と進める誘導をさせたい。**
フォームの入力項目を最小限にして、入力するストレスを減らす。
エラーなどの表示は解りやすく素早く表記して、ユーザーにストレスに感じさせない親切なフォームを目指す。

**- ナビゲーションの導線からもコンタクトフォームに遷移できる導線を作りたい。**
contactページを作成後、導線をつなぐ

**Comment by nina-fujioka** [comment]
とりあえず、これで問題ないです！あざます！

**Comment by onishi-nina** [comment]
要望を以下のようなまとめました。
以下のような実装をイメージしていますが、いかがでしょうか？
また、入力項目と1カラムの時に作成したデザインがあるかと思いますが、引き継ぎますか？

**↑そう１ここが大事です！**

**- ユーザーがフォーム入力をした後、指定のメアドにスムーズに届き、コニュニケーションを作りたい。**
- 指定したメアドにメールが送信される。
- 入力されたメアドに自動返信メールが送信される。


**- ユーザーが不便を感じずに送信完了まで自然と進める誘導をさせたい。**
- 必要な入力項目が表示されている。
- focus時のプレースフォルダーが表示される。
- それぞれの入力項目に対してのバリデーションが表示される。


**- ナビゲーションの導線からもコンタクトフォームに遷移できる導線を作りたい。**
- wordpressの管理画面からcontactページ作成する。

**Comment by nina-fujioka** [comment]
はーい、あざす！  
確認しまーす

**Comment by nina-fujioka** [comment]
俺の方でこのタイミング時に、こうしたらより良いのではと思うポイントを
まとめるからこれに関してレスください！  

▼**ヒアリング前の要望=準備**の整理 

ここで着目すべきポイント

- まず、当たり前をつくる整備をすること。  
↑そうしないとそもそもヒアリングポイントができない。情報を得られない・承認がとれない。
- どのようにすれば着手できるかを考える事  
↑デザインやページ追加の前提条件をつくる。なにもない状況から推測で着手はできない。プロとして言葉で説明されない部分を整備することがなにより大事。

- フォーム単体でとらえないこと。サイト内(/contact)のフォームであることを忘れない。
****

**Comment by nina-fujioka** [comment]
以下、コメントを残す前に考える事のサンプル。

**1.ユーザーがフォーム入力をした後、指定のメアドにスムーズに届き、コニュニケーションを作りたい。**  

これはヒアリング前の管理者・クライアントのやりたい要望=結果。  

じゃあ、これができるようにすればどうすればいいか。  
それを要望と現状を照らし合わせ考える。  

↓現状
wpサイトにはフォーム類はない。 

↓じゃあどうする  
wpサイト上にページをつくる。  

↓なんのページをつくるか  
フォーム入力・確認・送信 （３ページ＊２)  

↓どこに  
ほんとうに左カラムでOK？ここだけ1カラムとかないよね？？
↑ヒアリングポイントにもなる。

この3ページが揃った状況が  
管理者・クライアントにとっての「当たり前の状況」。  
俺がよくいう前提の条件。

ここまでを、まずは頭で考えていればOK。  

これが、ヒアリングの基本になり、工数の基本ベースになる。

↓なぜこれを考えるか  
前のconcrete5のフォーム確認画面の時のように、クライアントや管理者が思う当たり前ができない可能性があるから。  

フォームのページに限らず、「こういうもの」と相手と自分が勝手に認識しているところから考える事が大事。  

それがミスコミュを防ぎ、信頼されるようになるポイント。

**Comment by nina-fujioka** [comment]
以上を頭の中で整理するとコミットがこうなる。

▼ヒアリング前の要望を整理(施策者とのヒアリング前の準備・すり合わせ)

- ユーザーがフォーム入力をした後、指定のメアドにスムーズに届き、コニュニケーションを作りたい。
まず、その目的をつくる上で必要なページはフォーム入力→入力確認→確認ページで、問題ないか？  
  
- ユーザーが不便を感じずに送信完了まで自然と進める誘導をさせたい。
入力項目は以前にもらっている、項目内容でOK？  
それと、ほんとうに左カラムでOK？ここだけ1カラムとかないよね？  

- ナビゲーションの導線からもコンタクトフォームに遷移できる導線を作りたい。
contactページを作成後、**現状のナビゲーションからボタンを復活させ**導線をつなぐで問題ありませんか？(gutaitekini!!!)

**Comment by nina-fujioka** [comment]
ここで当たり前の条件ができる。 もし違う場合はすり合わせる。

ヒアリングや要件の定義・技術的な観点の話は、この状況を整えてから。  
全体像を見せて、整備しないと相手の「どうしたい」が引き出せず、結果として追加の修正と変更の連続になる。  

以上です。

**Comment by onishi-nina** [comment]
以下比較した時の反省点をまとめました。
もっと自分の思考を順を追って整理すべきでした。

- 自分の回答だと相手が思っている「当たり前」の全体像の共有する説明が足りなすぎ
- 相手のイメージを引き出すことすり合わせる確認が足りない
- 具体的にヒアリングポイントが提示できてないから、コミットの内容が「フォーム全体を作るのか」

「フォーム単体を作るのか」で明確に違う
- ↓ここを解消する言語が足りなすぎ（自分も勝手なイメージに引っ張られすぎて、そこの言語化が出来てない）

> フォームのページに限らず、「こういうもの」と相手と自分が勝手に認識しているところから考える事が大事。

**Comment by nina-fujioka** [comment]
あーLINEもしたけど、反省いらないよ！笑

**Comment by nina-fujioka** [comment]
目線として、先にそこを合わせると、自然と自分の世界に入らないと思うよーー

**Comment by nina-fujioka** [comment]
#141

**Comment by nina-fujioka** [comment]
次のSprintに移動します
