### ISSUE TITLE
フッター上の「あなたにオススメの記事」エリア改修

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#45]
**受け入れ条件**

1. 該当エリアのデザインが見やすくなっている。
2. デザインがhtmlで表示確認ができている。
3. cms側にソースを渡せる状態になっている。

**タスク分解**
後ほど記述

**備考**
> https://music.line.me/topics/all

- 背景や他コンテンツとの差別化を測るため、各サムネイルに枠が付いたパターンが欲しい。
- 参考は、https://music.line.me/topics/all
上記のサムネイルディテール。
- 画像サイズは現行の比率でOK。
- タイトル、テキストも現行同左寄せでOK。
- <a>タグで括る。</a>hover効果もできればお願いします。

参考サイト
> https://music.line.me/topics/all

**Comment by onishi-nina** [comment]
_thumbnail.scss
/service/design/index.html

**Comment by onishi-nina** [comment]
引き続き以下ファイルを編集します！

■編集予定ファイル
_thumbnail.scss
/service/design/index.html

**Comment by nina-fujioka** [comment]
クラス名
「p-related」→「l-related」に変更ください。

ファイルディレクトリ
project→layoutに変更。

**Comment by onishi-nina** [comment]
クラス名「c-thumbnail--largeboder」を追加
幅とmarginは「c-thumbnail--large」のままで枠線だけ追加
余白を調整するのに「_related.scss」を編集します。

以下ページにクラス名を追加したものをpushしました。
vagrant upの後、ご確認ください。

http://192.168.33.10/service/design/index.html
