### ISSUE TITLE
コンタクトフォーム実装

### ISSUE THREAD

**Issue by onishi-nina** [nina-dev/dev#71]
**受け入れ条件**

- ローカル上で確認できる。
- 必要な入力項目が表示されている。
- focus時のプレースフォルダーが表示される。
- 指定したメールアドレスにメールが送信される。
- 入力されたメールアドレスに自動返信メールが送信される。
- それぞれの入力項目に対してのバリデーションを実装。
- 「submit」完了後、完了画面に遷移する。（今後、確認画面への遷移を実装予定）

**タスク分解**
後ほど記述

**備考**

1. HTML側で表示されている項目をCMS側で表示
2. 入力項目に対して、適切な入力タイプを指定
3. focus時はjavascriptで判定し、css側でプレースフォルダーの表示・非表示を指定
4. CMSのデフォルトの機能を使用して、指定したメールアドレスにメールを送信
5. CMSのデフォルトの機能を使用して、入力がされたメールアドレスにメールを送信
6. 不正な入力値のとき、エラー内容がリアルタイムに表示される（フロント側で制限）

参考サイト

> https://liginc.co.jp/345545
> https://www.cherrypieweb.com/weblog/technical/20161207104805.php

**Comment by onishi-nina** [comment]
**開発用ブランチを作成**
外部フォームを作成しての実装になるため、CMSのコアファイルに影響がないように別のブランチを作成して構築。

**Comment by nina-fujioka** [comment]
これ、すごくいいよ！

**Comment by onishi-nina** [comment]
ありがとうございます！マネさせてもらいました！

**Comment by nina-fujioka** [comment]
ただ、日本語がちがうかなーーこれはね、このタイミングだと
やれることリストとしといたほうがいいと思う！

**Comment by nina-fujioka** [comment]
これはまったくまちがいじゃないんだけど、まずデザイナーとディレクターにやれることの提案って意味合いのほうがいいな

**Comment by nina-fujioka** [comment]
受け入れってのはこの次だね、もちろんこれでいいんだけど、すごく細かい話だと、エンジニアがこういった形をとるのは、この次だね

**Comment by onishi-nina** [comment]
確かに「やれること」「やること」の判断してからの受け入れってことですね

**Comment by nina-fujioka** [comment]
そうそう！

**Comment by nina-fujioka** [comment]
そもそも、やれることが分からない（もっとやれるだろ）と思ってる人にまず提示して、ボーダーを決めるコミュニケーションが必要。

**Comment by nina-fujioka** [comment]
で、そこからこれがいる、いらないを周知して形式上の承諾というか、参加させて責任を一緒に取らせる（巻き込む)ってことがすごく大事でさ

**Comment by nina-fujioka** [comment]
ま、間違いでもなく、すごく良いから今後の参考にしてもらえると！

**Comment by onishi-nina** [comment]
確かにその通りです！めっちゃ参考にさせてもらいます！

**Comment by nina-fujioka** [comment]
かなり前のめりでいいよ！

**Comment by nina-fujioka** [comment]
これもコミュニケーションで、テクニックでもあんだよね、

**Comment by nina-fujioka** [comment]
この作ってくれたissueもとにまた明日はなしましょー！

**Comment by onishi-nina** [comment]
ありがとうございます！お願いします！

**Comment by nina-fujioka** [comment]
vccwへの移行のためクローズ
