### ISSUE TITLE
vccwの設定・導入

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#86]
なるべくスピーディーに！
わからない点は抱え込まず共有くださーい。

**Comment by nina-fujioka** [comment]
目標は7/19中の導入とgitでのやりとりができるまで。

**Comment by onishi-nina** [comment]
vagrant upの後
/wp/provision/default.yml (Errno::ENOENT)
のエラーが表示されます。
「provision」フォルダは必要ですかね？

**Comment by nina-fujioka** [comment]
これ導入できたからclaseします
