### ISSUE TITLE
wpテンプレート作成

### ISSUE THREAD

**Issue by nina-fujioka** [nina-dev/dev#87]
一旦、既存のHTMLからじゃんじゃん制作していき、すべてのページが用意できている状態にする。  
HTMLの差分は次のスプリントからphpファイルで修正できる状態がベスト。

**Comment by onishi-nina** [comment]
■作成するページ
**トップページ**
index.php

**一覧**
category.php

**ニナ・アーキタイプについて**
page-about.php

**料金について**
page-price.php

**お仕事の流れ**
page-flow.php

**お問い合わせ**
page-contact.php

**投稿（article）**
single.php

**共通**
header.php
footer.php
sidebar.php

**Comment by onishi-nina** [comment]
コーディング着手中

**Comment by onishi-nina** [comment]
header.php内の記述を変更します。
p-menuを「template_parts」以下で管理。

**Comment by onishi-nina** [comment]
作成するページに「お問い合わせ」を追加

**Comment by nina-fujioka** [comment]
ダミーのデータからループ処理をして記事が表示されるまでお願いしまーす！

**Comment by nina-fujioka** [comment]
#105 に移行します
